### ISSUE TITLE
Fastlane: French short_description.txt is too long

### ISSUE THREAD

**Issue by IzzySoft** [ICTrust/PObY-A#10]
Fastlane `short_description.txt` is limited to 80 chars, everything beyond that is truncated. Your French one currently has 96 chars. Could you please shorten it? At the moment, it is cut in the middle of the previous-to-last word.

**Comment by A-YATTA** [comment]
Fixed on the release 1.5.1.

**Comment by IzzySoft** [comment]
Thanks!
