### ISSUE TITLE
Codeberg alternative

### ISSUE THREAD

**Issue by JonnyTech** [ICTrust/PObY-A#13]
I read from [another issue](https://github.com/ICTrust/PObY-A/issues/5#issuecomment-1502279649) that required app data is hosted on [codeberg.org](https://codeberg.org). Unfortunately that domain is blocked in my country. Can you possibly mirror it elsewhere?

**Comment by A-YATTA** [comment]
Sorry to hear that. 
Sure, the repository is now mirrored on [Github](https://github.com/ICTrust/mal-db) and it will be added on the next release.
