### ISSUE TITLE
Always crashes when trying to launch

### ISSUE THREAD

**Issue by A-7666** [ICTrust/PObY-A#15]
I'm not able to try the program, it constantly crashes when trying to launch it.
Both on AOSP 11 (/e/ OS) and AOSP 13 (GrapheneOS).
Program version PObY-A v1.5.1 [2023.06.27].

`UnknownHostException: unable to resolve host "codeberg.org": no address associated with hostname at Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:147) at <.....>`

Hope this can be fixed.

**Comment by A-YATTA** [comment]
Maybe that codeberg is blocked in your county ([issue 13](https://github.com/ICTrust/PObY-A/issues/13)). 
A fix will be provided for that. 
If you are using the source code, you can replace the database URL in Prefs.kt : https://codeberg.org/ by https://github.com/ .

**Comment by A-YATTA** [comment]
Fixed on #16. It will be available on the next release.

**Comment by A-YATTA** [comment]
Indeed, now the crash is "catched" and a Toast is shown if there is a connection problem. 
Please feel free to reopen the issue if the problem persist.
