### ISSUE TITLE
Trackers inside?

### ISSUE THREAD

**Issue by IzzySoft** [ICTrust/PObY-A#5]
> PObY-A, Privacy Owned by You - Android, is an application which aim to help Android users to improve security and privacy of their devices.

That sounds great! But…

```
Offending libs:
---------------
* Google Ads (/com/google/ads): Ads,NonFreeDep
* Play Services SafetyNet (/com/google/android/gms/safetynet): NonFreeDep,NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Cloud Audit Logs (/com/google/cloud/audit): Tracking
* Google Cloud Logging Client for Java (/com/google/cloud/logging): NonFreeNet
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* Firebase Analytics (/com/google/firebase/analytics): NonFreeDep,Tracking
* firebase-firestore (/com/google/firebase/firestore): NonFreeDep,NonFreeNet

8 offenders.
```

These are rather "privacy offenders" which somehow contradict the described purpose of your app. And (`NonFreeDep`) making it (at least partly) non-FOSS. Mind to remove those libraries? Or replace them by alternatives, if they are needed for the described functionality of your app? Thanks in advance!

PS: Replacements for most Firebase stuff include [Supabase](https://supabase.com/) and [appwrite](https://github.com/appwrite/appwrite), for starters. And if you really need analytics, see [here](https://gitlab.com/-/snippets/1896503#acceptable-analytics) for some FOSS alternatives (and please configure them to be opt-in, especially with an app that is about enhancing privacy :wink:)

**Comment by A-YATTA** [comment]
Many thanks for the feedback! 

Please find the comments bellow:

> * Google Ads (/com/google/ads): Ads,NonFreeDep

There is no Ads on the app, could you provide more information regarding this or which third party library use it ? 

> *  Play Services SafetyNet (/com/google/android/gms/safetynet): NonFreeDep,NonFreeNet

SafetyNet will be disabled.

> * Google Mobile Services (/com/google/android/gms): NonFreeDep

Not needed anymore as SafetyNet will be removed.

> * Firebase Analytics (/com/google/firebase/analytics): NonFreeDep,Tracking 

Disabled on the Firebase Console as it's not needed. 

> * firebase-firestore (/com/google/firebase/firestore): NonFreeDep,NonFreeNet
> * Firebase (/com/google/firebase): NonFreeNet,NonFreeDep

Supabase seems to be a good alternative, will be migrated on the next release. 

Thank you for your contribution.

**Comment by IzzySoft** [comment]
> There is no Ads on the app, could you provide more information regarding this or which third party library use it ?

Two steps. First to show it's there: you can use [Apktool](https://github.com/iBotPeaches/Apktool) to get the smali of the APK. Inside the generated folder, look for `smali*` folders, Inside there, you'll find `/com/google/ads` – which shows the library is there.

Second step: if you didn't add it yourself, how did it come there? For that, we need to create a dependency tree. Let me see: you use Kotlin with gradle, that should make this easy. `gradle :app:dependencies` should come to the rescue there.

Great to see you're going to remove the other proprietary dependencies, too! Note however that "disabling" Firebase in the console might not be sufficient and keep the libraries in. But that can be tackled one by one. Just let me know if you have a new APK (you can attach it here to the issue if you don't want to make a release right away), and I run it through the scanner again. Or you can do that yourself, as the scanner is free/libre and open source. [Identify modules in apps](https://android.izzysoft.de/articles/named/app-modules-2) is an article describing it and how to set it up and use it manually. It's also possible to include it with a CI – should you need that, I can point you to a source for that, too.

> Supabase seems to be a good alternative, will be migrated on the next release.

That sounds fantastic! :partying_face: Looking forward to the next APK then!

> Thank you for your contribution.

Gladly – and it rewards me a lot the way you pick up and implement my suggestions, thanks to you for that!

**Comment by A-YATTA** [comment]
Thank you for the details.

Indeed `com.google.android.gms:play-services-ads-identifier` is a dependency of `firebase-core` .

The database is now hosted on codeberg as a json file (https://codeberg.org/ICTrust/mal-db/src/branch/main/db-1.json) and a version file (https://codeberg.org/ICTrust/mal-db/src/branch/main/version) that specify the current version of the database. That's not the most elegant solution as I have had a few complications with the implementation of supabase using the [Kotlin Multiplatform Client](https://github.com/supabase-community/supabase-kt).

**Comment by IzzySoft** [comment]
Thanks for working on this! Unfortunately I cannot help with development specific things (I'm not an Android dev myself) – so I only can keep my fingers crossed that it doesn't get too complicated. I notice the "past tense", so I can hope you overcame the problems already (or most of them at least). If I can help some other way let me know; I cannot promise anything as my desk already is "full of papers", but I can see.

Codeberg sounds great, most of my projects are hosted there and I fully trust its crew (I know some of them personally).

Let me know when I shall run another APK through my scanners, or even check a new release if I can pick it up to provide it with [my F-Droid repo](https://apt.izzysoft.de/fdroid) :smiley:

**Comment by IzzySoft** [comment]
Thanks @A-YATTA – and sure I can give the new APK a run. Just give me a ping when it's available then.

**Comment by A-YATTA** [comment]
@IzzySoft could you please run the scanners on the attached APK (current dev branch) ? 

Thank you in advance.

PS: I renamed the file to ".zip" as attaching an ".apk" file is not allowed.

[PObY-A_1.5.zip](https://github.com/ICTrust/PObY-A/files/11615950/PObY-A_1.5.zip)

**Comment by IzzySoft** [comment]
> I renamed the file to ".zip" as attaching an ".apk" file is not allowed.

Haha, you at least know the tricks (as long as the mime-type matches, any extension can help) :see_no_evil:

Tested: looks clean, congrats!

**Comment by A-YATTA** [comment]
Indeed 😅

Many thanks for your contribution! Please feel free to add the new version to your repository.

I will close this issue, you can always reopen it if needed.

**Comment by IzzySoft** [comment]
Thanks! Will [show up here](https://apt.izzysoft.de/fdroid/index/apk/ch.ictrust.pobya) with the next sync around 6 pm UTC (i.e. in about 23h – just barely missed the last sync). If you want I can send you a PR with the metadata I've set up in Fastlane format, so you can control how your app is presented (description, graphics) by adjusting that (be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) then for this), just let me know if you want to have it. Updates to that structure would then be pulled along with new releases.

**Comment by A-YATTA** [comment]
Sounds great! 
Yes sure, the PR is very welcome. Shall we create a new issue for that ?

**Comment by IzzySoft** [comment]
Nah, a PR is just a special kind of issue anyway. Apologies for the delay, and there it is :smile:

**Comment by A-YATTA** [comment]
Thank you for your contribution

**Comment by IzzySoft** [comment]
Anytime!
